stages:
  - test
 
before_script:
  - cpanm Test::More
  - cpanm --installdeps .
  - perl Makefile.PL

unitTestsLatest:
    image: perl:latest
    stage: test
    script:
      - REPORT_TEST_ENVIRONMENT=1 perl Build test
      - cpanm DBI
      - REPORT_TEST_ENVIRONMENT=1 perl Build test
